openapi: "3.0.0"
info:
  version: 1.0.0
  title: Python Pod API
paths:
  /verify:
    get:
      summary: Filters HTTP Messages
      responses:
        '200':
          description: A JSON object indicating validity
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: string
                  time:
                    type: string

openapi: "3.0.0"
info:
  version: 1.0.0
  title: C Pod API
paths:
  /verify:
    get:
      summary: Logs HTTP messages
      responses:
        '200':
          description: A JSON object indicating validity
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: string
                  time:
                    type: string

openapi: "3.0.0"
info:
  version: 1.0.0
  title: Node Pod API
paths:
  /verify:
    get:
      summary: Filters HTTP Messages
      responses:
        '200':
          description: A JSON object indicating validity
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: string
                  time:
                    type: string